# Generated by Django 3.2.12 on 2022-04-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_onepunchman'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onepunchman',
            options={'verbose_name': 'onepunchman', 'verbose_name_plural': 'onepunchmen'},
        ),
    ]
