# Generated by Django 3.2.12 on 2022-04-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220428_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anime', verbose_name='Аниме'),
        ),
    ]
