# Generated by Django 4.0.3 on 2022-04-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_rating_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(default=0, upload_to='static/main/images/', verbose_name='Постер'),
            preserve_default=False,
        ),
    ]
