# Generated by Django 4.0.3 on 2022-04-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_anime_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=0, verbose_name='Эпизодов'),
        ),
    ]
