# Generated by Django 4.0.3 on 2022-04-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_anime_main_picture_alter_anime_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='video_url',
            field=models.TextField(default='', verbose_name='Ссылка на аниме'),
        ),
    ]
